#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00


# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Dan Bullock


module load singularity 2> /dev/null

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiledmatlab/main
